name: rpg_geo
description: A rpg game with geolocalization.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

flutter:
  uses-material-design: true